/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author nghia
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        rbWindows = new javax.swing.JRadioButton();
        rbSQL = new javax.swing.JRadioButton();
        jLabelPwd = new javax.swing.JLabel();
        jPasswordFieldPwd = new javax.swing.JPasswordField();
        jLabelConfirm = new javax.swing.JLabel();
        jPasswordFieldConfirm = new javax.swing.JPasswordField();
        jCheckBoxPolicy = new javax.swing.JCheckBox();
        jCheckBoxExpiration = new javax.swing.JCheckBox();
        jCheckBoxMustChange = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel1.setText("Login name:");

        rbWindows.setText("Windows Authentication");

        rbSQL.setText("SQL Server Authentication");
        rbSQL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbSQLItemStateChanged(evt);
            }
        });

        jLabelPwd.setText("Password:");
        jLabelPwd.setEnabled(false);

        jPasswordFieldPwd.setEnabled(false);

        jLabelConfirm.setText("Confirm Password:");
        jLabelConfirm.setEnabled(false);

        jPasswordFieldConfirm.setEnabled(false);

        jCheckBoxPolicy.setText("Enforce password policy");
        jCheckBoxPolicy.setEnabled(false);

        jCheckBoxExpiration.setText("Enforce password expiration");
        jCheckBoxExpiration.setEnabled(false);

        jCheckBoxMustChange.setText("User must change password at next login");
        jCheckBoxMustChange.setEnabled(false);

        jLabel4.setText("Default database");

        jComboBox1.setMaximumRowCount(15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPwd)
                                    .addComponent(jLabelConfirm))
                                .addGap(145, 145, 145)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordFieldPwd)
                                    .addComponent(jPasswordFieldConfirm)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxPolicy)
                                    .addComponent(jCheckBoxMustChange)
                                    .addComponent(jCheckBoxExpiration))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(177, 177, 177)
                        .addComponent(jComboBox1, 0, 120, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbWindows)
                            .addComponent(rbSQL))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(203, 203, 203)
                        .addComponent(jTextField1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbWindows)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbSQL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPwd)
                    .addComponent(jPasswordFieldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConfirm)
                    .addComponent(jPasswordFieldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxPolicy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxExpiration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxMustChange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbSQLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbSQLItemStateChanged
        // TODO add your handling code here:
        System.out.println("rbSQL select");
        if (rbSQL.isSelected()) {
            jLabelPwd.setEnabled(true);
            jLabelConfirm.setEnabled(true);
            jPasswordFieldConfirm.setEnabled(true);
            jPasswordFieldPwd.setEnabled(true);
            jCheckBoxExpiration.setEnabled(true);
            jCheckBoxMustChange.setEnabled(true);
            jCheckBoxPolicy.setEnabled(true);
        }else{
            jLabelPwd.setEnabled(false);
            jLabelConfirm.setEnabled(false);
            jPasswordFieldConfirm.setEnabled(false);
            jPasswordFieldPwd.setEnabled(false);
            jCheckBoxExpiration.setEnabled(false);
            jCheckBoxMustChange.setEnabled(false);
            jCheckBoxPolicy.setEnabled(false);
        }
    }//GEN-LAST:event_rbSQLItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxExpiration;
    private javax.swing.JCheckBox jCheckBoxMustChange;
    private javax.swing.JCheckBox jCheckBoxPolicy;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelConfirm;
    private javax.swing.JLabel jLabelPwd;
    private javax.swing.JPasswordField jPasswordFieldConfirm;
    private javax.swing.JPasswordField jPasswordFieldPwd;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rbSQL;
    private javax.swing.JRadioButton rbWindows;
    // End of variables declaration//GEN-END:variables
}
