USE QLTV
GO


-- CUONSACH
GO
CREATE TRIGGER TR_AFTERINSERT_SACH
ON CUONSACH
AFTER INSERT
AS
BEGIN
	DECLARE @MAS NCHAR(10), @SLSACH INT, @SLSACHNHAP INT, @MADS NCHAR(10)
	SELECT @MAS = MAS FROM inserted
	SELECT @MADS = MADS FROM inserted
	SELECT @SLSACH = (COUNT(MADS)) FROM CUONSACH WHERE MADS = @MADS
	SELECT @SLSACHNHAP = SUM(SLSACHNHAP) FROM CTNHAP WHERE MADS = @MADS

	IF(@SLSACH <= @SLSACHNHAP)
		BEGIN
			UPDATE DAUSACH SET SL_CO_SAN = SL_CO_SAN + 1 WHERE MADS = @MADS
		END
	ELSE 
		RAISERROR (N'SỐ LƯỢNG SÁCH ĐÃ ĐẠT TỐI ĐA KHÔNG THỂ THÊM!',16,1)
END

GO
CREATE TRIGGER TR_AFTERDELETE_SACH
ON CUONSACH
AFTER DELETE
AS
BEGIN
	DECLARE @MAS NCHAR(10), @SOPHIEUTL NCHAR(10)
	SELECT @MAS = MAS FROM deleted
	SELECT @SOPHIEUTL = SOPHIEUTL FROM deleted
	IF(@SOPHIEUTL IS NOT NULL)
		RAISERROR (N'SÁCH ĐÃ THANH LÝ KHÔNG THỂ XÓA!', 16, 1)
	ELSE 
		UPDATE DAUSACH SET SL_CO_SAN = SL_CO_SAN - 1 WHERE MADS = (SELECT MADS FROM deleted)
END

GO
CREATE TRIGGER TR_AFTERUPDATE_SACH
ON CUONSACH
AFTER UPDATE
AS
BEGIN 
	DECLARE @MADS NCHAR(10), @DAMUON BIT, @MAS NCHAR(10), @SOPHIEUTL NCHAR(10)
	SELECT @MAS = MAS FROM inserted
	SELECT @MADS = MADS FROM inserted
	SELECT @DAMUON = DAMUON FROM inserted
	SELECT @SOPHIEUTL = SOPHIEUTL FROM INSERTED 
	IF(UPDATE(SOPHIEUTL))
		IF(@SOPHIEUTL IS NOT NULL)
			IF(@DAMUON = 0)
				BEGIN
					UPDATE PHIEUTHANHLY SET SOSACHTL = SOSACHTL + 1 WHERE SOPHIEUTL = @SOPHIEUTL 
					UPDATE DAUSACH SET SL_CO_SAN = SL_CO_SAN - 1 WHERE MADS = @MADS	
				END
		ELSE IF(@SOPHIEUTL IS NULL)
			RAISERROR (N'KHÔNG THỂ LẤY LẠI NHỮNG CUỐN SÁCH ĐÃ THANH LÝ!', 16,1)

	IF(UPDATE(KIEUMUON))
		IF(@SOPHIEUTL IS NOT NULL OR @DAMUON = 1)
		BEGIN
				RAISERROR (N'SÁCH ĐANG MƯỢN HOẶC ĐÃ THANH LÝ! KHÔNG THỂ THAY ĐỔI KIỂU MƯỢN!',16,1)
		END
END


GO
-- PHIEUMUONTRA
CREATE TRIGGER TR_AFTERINSERT_PHIEUMUONTRA
ON PHIEUMUONTRA
AFTER INSERT 
AS
BEGIN
	UPDATE PHIEUMUONTRA SET NGAYHENTRA = DATEADD( DAY, 7, (SELECT NGAYMUON FROM inserted) ) WHERE SOPHIEU = (SELECT SOPHIEU FROM inserted)
END


-- CTMUONTRA
GO
ALTER TRIGGER TR_AFTERINSERT_CTMUONTRA
ON CTMUONTRA
AFTER INSERT 
AS
BEGIN 
	DECLARE @MAS NCHAR(10), @SOPHIEUTL NCHAR (10), @MADS NCHAR(10), @DAMUON BIT, @KIEUMUON NCHAR(3), @NGAYMUON DATE, @SOPHIEU NCHAR(10)
	SELECT @MAS = MAS FROM INSERTED
	SELECT @SOPHIEU = SOPHIEU FROM INSERTED
	SELECT @MADS = MADS FROM CUONSACH WHERE MAS = @MAS
	SELECT @SOPHIEUTL = SOPHIEUTL FROM CUONSACH WHERE MAS = @MAS
	SELECT @DAMUON= DAMUON FROM CUONSACH WHERE MAS= @MAS
	SELECT @KIEUMUON= KIEUMUON FROM CUONSACH WHERE MAS= @MAS
	SELECT @SOPHIEUTL= SOPHIEUTL FROM CUONSACH WHERE MAS= @MAS
	SELECT @NGAYMUON = NGAYMUON FROM PHIEUMUONTRA WHERE SOPHIEU = @SOPHIEU

	IF(@SOPHIEUTL IS NULL)
			BEGIN
				IF(@KIEUMUON IN ('CPM') )
					BEGIN
						IF(@DAMUON = 0)
							BEGIN
								UPDATE CUONSACH SET DAMUON = 1 WHERE MAS = @MAS 
								UPDATE PHIEUMUONTRA SET TONGSACH = TONGSACH + 1 WHERE SOPHIEU = (SELECT SOPHIEU FROM INSERTED)
								UPDATE DAUSACH SET SL_CO_SAN = SL_CO_SAN - 1 WHERE MADS = @MADS
							END
						ELSE
							RAISERROR (N'SÁCH ĐÃ ĐƯỢC MƯỢN!', 16,1)
					END
				ELSE
					RAISERROR (N'SÁCH KHÔNG ĐƯỢC MƯỢN!', 16,1)
			END
	ELSE
		RAISERROR (N'SÁCH ĐÃ THANH LÝ!', 16,1)
END


GO
CREATE TRIGGER TR_AFTERDELETE_CTMUONTRA
ON CTMUONTRA
AFTER DELETE
AS
BEGIN
	DECLARE @MADS NCHAR(10), @MAS NCHAR(10), @NGAYMUON DATE, @PHIEUMUON NCHAR(10)
	SELECT @MAS = MAS FROM deleted
	SELECT @MADS = MADS FROM CUONSACH WHERE MAS = @MAS
	SELECT @PHIEUMUON = SOPHIEU FROM deleted
	SELECT @NGAYMUON = NGAYMUON FROM PHIEUMUONTRA WHERE SOPHIEU = @PHIEUMUON

	IF(@NGAYMUON = GETDATE())
		BEGIN
			UPDATE CUONSACH SET DAMUON = 0 WHERE MAS = (SELECT MAS FROM deleted)
			UPDATE PHIEUMUONTRA SET TONGSACH = TONGSACH - 1 WHERE SOPHIEU = (SELECT SOPHIEU FROM deleted)
			UPDATE DAUSACH SET SL_CO_SAN = SL_CO_SAN + 1 WHERE MADS = @MADS
		END
	ELSE IF (@NGAYMUON < GETDATE())
		RAISERROR (N'KHÔNG THỂ XÓA VÌ ĐÃ MƯỢN QUÁ 1 NGÀY!', 16,1)
END



GO
ALTER TRIGGER TR_AFTERUPDATE_CTMUONTRA
ON CTMUONTRA
AFTER UPDATE
AS
BEGIN 
	IF(UPDATE(NGAYTRA))
		DECLARE @NGAYTRA DATE, @NGAYHENTRA DATE, @SOPHIEU NCHAR(10), @MATT NCHAR(10), @MADS NCHAR(10), @MAS NCHAR(10)
		SELECT @NGAYTRA = NGAYTRA, @SOPHIEU = SOPHIEU FROM inserted
		SELECT @NGAYHENTRA = NGAYHENTRA FROM PHIEUMUONTRA WHERE SOPHIEU = @SOPHIEU
		SELECT @MATT = MATT FROM inserted
		SELECT @MAS = MAS FROM inserted
		SELECT @MADS = MADS FROM CUONSACH WHERE MAS = @MAS
		IF(@MATT IS NOT NULL)
		BEGIN
			IF (@NGAYTRA IS NOT NULL)
				BEGIN
					IF(@NGAYTRA > @NGAYHENTRA)
						BEGIN
							UPDATE CTMUONTRA SET GHICHU = N'QUÁ NGÀY HẸN TRẢ' WHERE SOPHIEU = @SOPHIEU AND MAS = (SELECT MAS FROM inserted)
							UPDATE CUONSACH SET DAMUON = 0 WHERE MAS = (SELECT MAS FROM inserted) --SLCS
							UPDATE DAUSACH SET SL_CO_SAN = SL_CO_SAN + 1 WHERE MADS = @MADS
						END
					ELSE IF(@NGAYTRA <= @NGAYHENTRA)
						BEGIN
							UPDATE CTMUONTRA SET GHICHU = '' WHERE SOPHIEU = @SOPHIEU AND MAS = (SELECT MAS FROM inserted)
							UPDATE CUONSACH SET DAMUON = 0 WHERE MAS = (SELECT MAS FROM inserted)
							UPDATE DAUSACH SET SL_CO_SAN = SL_CO_SAN + 1 WHERE MADS = @MADS
						END
				END
			ELSE IF (@NGAYTRA IS NULL)
				BEGIN
					UPDATE CTMUONTRA SET GHICHU = '' WHERE SOPHIEU = @SOPHIEU AND MAS = (SELECT MAS FROM inserted)
					UPDATE CUONSACH SET DAMUON = 1 WHERE MAS = (SELECT MAS FROM inserted)
					UPDATE DAUSACH SET SL_CO_SAN = SL_CO_SAN - 1 WHERE MADS = @MADS
				END
		END
		ELSE 
			RAISERROR (N'CHƯA NHẬP MÃ THỦ THƯ!', 16,1)
END